
start_0: {x: -7.5, y: 0.0, z: 2.0}
goal_0: {x: 7.5, y: 0.0, z: 2.0}

start_1: {x: 7.5, y: 0.0, z: 2.0}
goal_1: {x: -7.5, y: 0.0, z: 2.0}

start_2: {x: 0.0, y: 7.5, z: 2.0}
goal_2: {x: 0.0, y: -7.5, z: 2.0}

start_3: {x: 0.0, y: -7.5, z: 2.0}
goal_3: {x: 0.0, y: 7.5, z: 2.0}

start_4: {x: 5.3, y: 5.3, z: 2.0}
goal_4: {x: -5.3, y: -5.3, z: 2.0}

start_5: {x: -5.3, y: -5.3, z: 2.0}
goal_5: {x: 5.3, y: 5.3, z: 2.0}

start_6: {x: 5.3, y: -5.3, z: 2.0}
goal_6: {x: -5.3, y: 5.3, z: 2.0}

start_7: {x: -5.3, y: 5.3, z: 2.0}
goal_7: {x: 5.3, y: -5.3, z: 2.0}


start_8: {x: 6.92, y: 2.87, z: 2.0}
goal_8: {x: -6.92, y: -2.87, z: 2.0}

start_9: {x: -6.92, y: -2.87, z: 2.0}
goal_9: {x: 6.92, y: 2.87, z: 2.0}

start_10: {x: -6.92, y: 2.87, z: 2.0}
goal_10: {x: 6.92, y: -2.87, z: 2.0}

start_11: {x: 6.92, y: -2.87, z: 2.0}
goal_11: {x: -6.92, y: 2.87, z: 2.0}

start_12: {x: 2.87, y: 6.92, z: 2.0}
goal_12: {x: -2.87, y: -6.92, z: 2.0}

start_13: {x: -2.87, y: -6.92, z: 2.0}
goal_13: {x: 2.87, y: 6.92, z: 2.0}

start_14: {x: -2.87, y: 6.92, z: 2.0}
goal_14: {x: 2.87, y: -6.92, z: 2.0}

start_15: {x: 2.87, y: -6.92, z: 2.0}
goal_15: {x: -2.87, y: 6.92, z: 2.0}